export default {
  palette:{
  primary:{
    light:'#78909c',
    main:"#2f2fa2",
    dark:'#0097a7',
    contrastText:'#ffffff'
  },
  secondary:{
    light:'#212121',
    main:"#f64c72",
    dark:'#1de9b6',
    contrastText:'#ffffff'
  }
},
  typography:{
    userNextVariants:true
  }
}